name: pdfrx
description: pdfrx is a rich and fast PDF viewer implementation built on the top of PDFium. The plugin supports Android, iOS, Windows, macOS, Linux, and Web.
version: 1.0.101
homepage: https://github.com/espresso3389/pdfrx
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  collection: '>=1.18.0 <1.20.0'
  crypto: ^3.0.6
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  http: ^1.2.2
  path: ^1.9.0
  path_provider:
    git: https://github.com/kumsumit/path_provider.git
  rxdart: '>=0.27.0 <0.29.0'
  synchronized: ^3.3.0
  url_launcher:
    git: https://github.com/kumsumit/url_launcher.git
  vector_math: ^2.1.4
  web: ^1.1.0

dev_dependencies:
  ffigen: ^16.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  archive: ^4.0.2

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
        sharedDarwinSource: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
        sharedDarwinSource: true
      windows:
        ffiPlugin: true

# dart run ffigen
ffigen:
  output:
    bindings: "lib/src/pdfium/pdfium_bindings.dart"
  headers:
    entry-points:
      - "example/viewer/build/windows/x64/.lib/latest/include/fpdfview.h"
      - "example/viewer/build/windows/x64/.lib/latest/include/fpdf_annot.h"
      - "example/viewer/build/windows/x64/.lib/latest/include/fpdf_text.h"
      - "example/viewer/build/windows/x64/.lib/latest/include/fpdf_doc.h"
      - "example/viewer/build/windows/x64/.lib/latest/include/fpdf_edit.h"
      - "example/viewer/build/windows/x64/.lib/latest/include/fpdf_formfill.h"
    include-directives:
      - "example/viewer/build/windows/x64/.lib/latest/include/**"
  preamble: |
    // ignore_for_file: unused_field
  name: "pdfium"
