name: pdfrx_wasm
description: This is a satellite plugin for pdfrx that allows you to use WASM version of Pdfium.
version: 1.1.6
homepage: https://github.com/espresso3389/pdfrx

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:

  assets:
    - assets/
